config/routes.rb
RubyBench::Application.routes.draw do

  # Small hack for creating benchmark by some template
  post 'benchmarks/new' => 'sample_groups#new'

  resources :sample_groups, path: 'benchmarks' do
    get 'results', :to => 'sample_groups#results'

    if Rails.env.development?
      member do
        get 'run' => 'sample_groups#run'
      end
    end
  end

  root :to => 'home#index'


end

app/models/sample.rb
class Sample < ActiveRecord::Base
  belongs_to :sample_group

  validates_presence_of :code
  before_save :validate_code

  private

  def validate_code
    policy = RubyCop::Policy.new
    ast = RubyCop::NodeBuilder.build(self.code)
    unless ast.accept(policy)
      errors.add(:sample_group, 'Unsafe code')
      return false
    end
  end

end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy]

  # GET /samples
  # GET /samples.json
  def index
    @samples = Sample.all
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(sample_params)

    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sample }
      else
        format.html { render action: 'new' }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params
      params[:sample]
    end
end

app/views/samples/_form.html.slim
= form_for @sample do |f|
  - if @sample.errors.any?
    .alert.alert-danger#error_explanation
      h2 = "#{pluralize(@sample.errors.count, "error")} prohibited this sample from being saved:"
      ul.text-danger
        - @sample.errors.full_messages.each do |message|
          li = message

  .actions = f.submit 'Save'

app/views/samples/edit.html.slim
h1 Editing sample

== render 'form'

= link_to 'Show', @sample
'|
= link_to 'Back', samples_path

app/views/samples/index.html.slim
h1 Listing samples

table
  tr
    th
    th
    th

  - @samples.each do |sample|
    tr
      td = link_to 'Show', sample
      td = link_to 'Edit', edit_sample_path(sample)
      td = link_to 'Destroy', sample, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Sample', new_sample_path

app/views/samples/new.html.slim
h1 New sample

== render 'form'

= link_to 'Back', samples_path

app/views/samples/show.html.slim
p#notice = notice


= link_to 'Edit', edit_sample_path(@sample)
'|
= link_to 'Back', samples_path