config/routes.rb
RubyBench::Application.routes.draw do

  # Small hack for creating benchmark by some template
  post 'benchmarks/new' => 'sample_groups#new'

  resources :sample_groups, path: 'benchmarks' do
    get 'results', :to => 'sample_groups#results'

    if Rails.env.development?
      member do
        get 'run' => 'sample_groups#run'
      end
    end
  end

  root :to => 'home#index'


end

app/models/sample_group.rb
class SampleGroup < ActiveRecord::Base

  has_many :samples
  accepts_nested_attributes_for :samples, :allow_destroy => true

  validates_presence_of :title

  def samples_results
    samples = self.samples

    data = []
    samples_results = []

    data << {title: self.title, description: self.description}

    samples.each do |sample|
      samples_results << {id: sample.id, title: sample.status, status: sample.status, systime: sample.sys_time, realtime: sample.real_time,
                          usertime: sample.user_time, memory: sample.memory}
    end
    data << {samples: samples_results}
  end

  def run_benchmark
    raise RuntimeError 'Cannot run benchmark for unsaved SampleGroup' if new_record?

    samples.each do |sample|
      sample.update_attributes!(status: SampleStatus::PENDING) unless sample.status
    end

    Performator.new.delay.run(self.id)
  end

  def slowest_sample
    samples.maximum(:real_time)
  end

  def largest_sample
    samples.maximum(:memory)
  end


end

app/controllers/sample_groups_controller.rb
class SampleGroupsController < ApplicationController

  before_action :set_sample_group, only: [:show, :edit, :update, :run]


  def index
    @sample_groups = SampleGroup.order('updated_at DESC').paginate(:page => params[:page], :per_page => 6)
    @demo_group = SampleGroup.new(title: 'Benchmark demo')
    @demo_group.samples.build(title: 'Test sample', code: sample_code)
  end


  def show
  end


  def new
    b_params = params[:sample_group] ? sample_group_params : nil

    @sample_group = SampleGroup.new(b_params)
    @sample_group.samples.build(code: sample_code) if @sample_group.samples.empty?
  end


  def edit
  end


  def create
    @sample_group = SampleGroup.new(sample_group_params)

    if @sample_group.save
      @sample_group.run_benchmark

      redirect_to @sample_group, notice: 'Benchmark was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @sample_group.update(sample_group_params)
      @sample_group.run_benchmark

      redirect_to @sample_group, notice: 'Benchmark was successfully updated.'
    else
      render action: 'edit'
    end
  end


  def run
    @sample_group.run_benchmark
    redirect_to sample_group_path(@sample_group)
  end

  def results
    sample_group = SampleGroup.find(params[:sample_group_id])
    @data = sample_group.samples_results
    render json: @data
  end

  private

  def sample_code
    <<CODE
# init (do not delete the comment)
# please write your initialization code below
arr = [0] * 1_000

# benchmark (do not delete the comment)
# please write your code to test below
1000000.times do
  arr.size
end
CODE
  end

  def set_sample_group
    @sample_group = SampleGroup.find(params[:id])
  end

  def sample_group_params
    params[:sample_group].permit(:id, :title, :description,
                                 samples_attributes: [:id, :title, :code, :_destroy])
  end

end

app/views/sample_groups/_form.html.slim
= simple_nested_form_for @sample_group, url: @sample_group.new_record? ? sample_groups_path : sample_group_path(@sample_group), \
                                 html: {class: 'form-horizontal'} do |f|
  - if @sample_group.errors.any?
    .row
      .col-lg-offset-2.col-lg-6
        .alert.alert-danger#error_explanation
          ul.text-danger
            - @sample_group.errors.full_messages.each do |message|
              li = message

  .form-group class = (@sample_group.errors[:title].blank? ? '' : 'has-error')
    = f.label :title, class: 'col-lg-2 control-label', required: true
    .col-lg-6
      = f.text_field :title, class: 'form-control'


  .form-group
    = f.label :description, class: 'col-lg-2 control-label'
    .col-lg-6
      = f.text_area :description, class: 'form-control', placeholder: 'Type some description here'


  = render partial: 'sample_groups/samples', locals: {f: f}




  .form-group
    - if @sample_group.new_record?
      .col-lg-offset-2.col-lg-6
        button.btn.btn-lg.btn-success.btn-block type="submit" Start benchmark!

    - else
      .col-lg-2
        = link_to 'Back to results', @sample_group, class: 'btn btn-default btn-block btn-lg'

      .col-lg-6
        button.btn.btn-lg.btn-success.btn-block type="submit" Start benchmark!

app/views/sample_groups/_sample.html.slim
.sample-info data-sample-id=sample.id
  h3
    .state-icon
      i.icon-cog
    = sample.title

  -if sample.error
    .errors_row
      = sample.error


  .highlight

    = text_area_tag "sample_#{sample.id}", sample.code, class: 'code', readonly: 'readonly'

  .sample-stats
    .param
      span Sys Time
      .val-sys-time= format_time(sample.sys_time)

    .param
      span User Time
      .val-user-time= format_time(sample.user_time)

    .param
      span Real Time
      .val-real-time= format_time(sample.real_time)

    .param
      span Memory
      .val-memory= number_to_human_size(sample.memory)

app/views/sample_groups/_sample_gorup.html.slim
.benchmark-preview
  .well.well-small
    h3
      = link_to sample_group.title, sample_group_path(sample_group.id)
    .description= sample_group.description

    .samples data-max-time=sample_group.slowest_sample
      - sample_group.samples.each do |sample|
        .sample
          .sample-scale
            .bar data-time=sample.real_time
            span.col-lg-2.sample-time #{sample.real_time} s
            .col-lg-10= sample.title

app/views/sample_groups/_sample_group.html.slim
.benchmark-preview
  h3
    = link_to sample_group.title, sample_group_path(sample_group.id)
  .description= sample_group.description

  table class='table table-bordered sample-results'
    tr
      th.time Time
      th.memory Memory
      th.title Title
      th.status Status
    - slowest = sample_group.slowest_sample
    - largest = sample_group.largest_sample
    - sample_group.samples.each do |sample|
      tr
        td.time
          .progress
            = format_time(sample.real_time) if calc_percentage(sample.real_time, slowest) < 40
            .progress-bar.progress-bar-success style="width: #{calc_percentage(sample.real_time, slowest)}%;"
              = format_time(sample.real_time) unless calc_percentage(sample.real_time, slowest) < 40

        td.memory
          .progress
            = format_time(sample.memory) if calc_percentage(sample.memory, largest) < 40
            .progress-bar style="width: #{calc_percentage(sample.memory, largest)}%;"
              = number_to_human_size(sample.memory) unless calc_percentage(sample.memory, largest) < 40

        td.title= sample.title.truncate(80)
        td.status= format_status(sample.status)

app/views/sample_groups/_samples.html.slim
.benchmark-sample#samples
  = f.simple_fields_for :samples do |ef|
    hr
    .form-group
      = ef.label :title, 'Code sample title', class: 'col-lg-2 control-label'
      .col-lg-6
        = ef.text_field :title, class: 'form-control', placeholder: 'Code sample title'
      .col-lg-2= ef.link_to_remove 'Remove sample', class: 'btn btn-danger'

    .form-group class = (@sample_group.errors["samples.code"].blank? ? '' : 'has-error')
      abbr title="required"
        = ef.label :code, '* Code sample', class: 'col-lg-2 control-label', :value => 'oo'
      .col-lg-6
        = ef.text_area :code, class: 'form-control code'

.form-group
  .col-lg-offset-2.col-lg-6
    = f.link_to_add :samples, class: 'btn btn-primary pull-right', id: :add_sample_btn, data: {target: '#samples'} do
      = icon_label('plus', 'Add code sample', white: false)

app/views/sample_groups/edit.html.slim
.form-group.clearfix
  .col-lg-offset-2.col-lg-6 style='padding-left: 0'
    h1 Edit Benchmark

= render 'form'

app/views/sample_groups/index.html.slim
h2 Latest benchmarks

.benchmarks.col-lg-16
  = render partial: 'sample_group', collection: @sample_groups

= will_paginate @sample_groups

- content_for :js
  coffee:
    $ ->
      App.initSampleGroupsPreview()
      return

app/views/sample_groups/new.html.slim
.form-group.clearfix
  .col-lg-offset-2.col-lg-6 style='padding-left: 0'
    h1 New Benchmark


= render partial: 'sample_groups/form'

app/views/sample_groups/show.html.slim
= link_to 'Edit', edit_sample_group_path(@sample_group), class: 'btn btn-primary btn-lg pull-right'
h1= @sample_group.title

p= @sample_group.description

hr

- @sample_group.samples.each do |sample|
  = render partial: 'sample', locals: {sample: sample}

table class='table table-bordered sample-results sample-detailed-results'
  tr
    th.title Title
    th.status Status
    th.time Real Time
    th.time Sys Time
    th.time User Time
    th.memory Memory
  - slowest = @sample_group.slowest_sample
  - largest = @sample_group.largest_sample
  - @sample_group.samples.each do |sample|
    tr
      td.title= sample.title.truncate(80)
      td.status= format_status(sample.status)
      td.time
        .progress
          = format_time(sample.real_time) if calc_percentage(sample.real_time, slowest) < 40
          .progress-bar.progress-bar-success style="width: #{calc_percentage(sample.real_time, slowest)}%;"
            = format_time(sample.real_time) unless calc_percentage(sample.real_time, slowest) < 40

      td.time
        .progress
          = format_time(sample.sys_time) if calc_percentage(sample.sys_time, slowest) < 40
          .progress-bar.progress-bar-success style="width: #{calc_percentage(sample.sys_time, slowest)}%;"
            = format_time(sample.sys_time) unless calc_percentage(sample.sys_time, slowest) < 40

      td.time
        .progress
          = format_time(sample.user_time) if calc_percentage(sample.user_time, slowest) < 40
          .progress-bar.progress-bar-success style="width: #{calc_percentage(sample.user_time, slowest)}%;"
            = format_time(sample.user_time) unless calc_percentage(sample.user_time, slowest) < 40

        td.usertime
          .progress
            = format_time(sample.user_time) if calc_percentage(sample.user_time, slowest) < 40
            .progress-bar.progress-bar-success style="width: #{calc_percentage(sample.user_time, slowest)}%;"
              = format_time(sample.user_time) unless calc_percentage(sample.user_time, slowest) < 40

        td.memory
          .progress
            = format_time(sample.memory) if calc_percentage(sample.memory, largest) < 40
            .progress-bar style="width: #{calc_percentage(sample.memory, largest)}%;"
              = number_to_human_size(sample.memory) unless calc_percentage(sample.memory, largest) < 40


- content_for :js
  coffee:
    App.initSamplePing(1)