config/routes.rb
RubyBench::Application.routes.draw do

  # Small hack for creating benchmark by some template
  post 'benchmarks/new' => 'sample_groups#new'

  resources :sample_groups, path: 'benchmarks' do
    get 'results', :to => 'sample_groups#results'

    if Rails.env.development?
      member do
        get 'run' => 'sample_groups#run'
      end
    end
  end

  root :to => 'home#index'


end

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class=("alert alert-#{name == :notice ? 'success' : 'error'}")
      a.close data-dismiss="alert"  ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
ul class="nav navbar-nav"
 li = link_to image_tag('logo.png'), root_path
 li = link_to 'Ruby Bench', root_path, :class => 'navbar-brand'
 li = link_to 'Create New', new_sample_group_path, :class => 'dropdown'
 li = link_to 'All Benchmarks',  sample_groups_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="width=device-width, initial-scale=1.0" name="viewport" 
    title= content_for?(:title) ? yield(:title) : 'Ruby Bench'
    meta content=(content_for?(:description) ? yield(:description) : 'Ruby Bench') name="description"
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = yield(:head)

  body class=("#{controller_name} #{action_name}")

    .navbar.navbar-default.navbar-fixed-top role="navigation"
      .container
        .navbar-header
          = render 'layouts/navigation'


    .container
      = render 'layouts/messages'
      = yield
      footer
    /! ! end of .container


    = yield :js